---
title: "Nuclear Arms Races. Who Is More Responsible?"
author: 
  - Sarıyüce, Abdulhakim[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{english}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== FOOTNOTES ============================== -->
<!-- ======================================================================= -->
[^1]:20080399, [Github Repo](https://github.com/abdulhkmsrc/mid-term)

# Introduction
The second world war ended in 1945 with two nuclear explosion in Japan, Nagasaki and Hiroshima. After that situation, the importance of nuclear power was understood by allied powers that were able to be named as winners of the second world war. After that war, the cold war began. Old allies became new enemies. In order to win the arms race, two enemies started developing nuclear weapons and tested them in deserts, oceans, islands and etc [@jacobs2013nuclear]. Different explosion methods, different nuclear energy sources were used in order to find perfect way to create the perfect Armageddon weapon. Luckily, there has been no usage of nuclear power to destroy a nation. However, as I have said before, these weapons were tested and these tests have harmed our environment in a very bad way. In my article, my aim is to find which country is more responsible for these harmful actions that have been created by nuclear explosions. I have found my data from https://github.com/rfordatascience/tidytuesday/tree/master/data and the name of my data is "nuclear explosions" This data include 1,382 observations with 16 columns. These columns include country names, nuclear explosion sources, year, purpose and the others. I have selected this data to figure out which country harmed most by creating nuclear explosions. 
To put my purpose, aim into reality, I have chosen my research question as **Which country is more responsible for the damage to the environment that live in and living life forms due to nuclear explosions?** I have found academic articles that are relevant to my question and help to reach my aim, however I have chosen four of them to review.      

## Literature Review
It is a very well documented fact that nuclear explosions destroy our environment and our own bodies @arda2006nukleer. It can be understood from the data I have chosen and the @ruff2015humanitarian that the huge majority of nuclear explosions have happened due to testing nuclear weapons. @ruff2015humanitarian says quote: "Apart from the two bombs dropped on Hiroshima and Nagasaki, and 150 explosions which were ostensibly “peaceful”,
3 the rest have been for the purpose of developing new nuclear weapons (making them more destructive, more compact and more deliverable), understanding their effects and developing plans for their use." Because of these test people that have lived in these test regions, **Pacific Ocean**, may develop genetic mutations and these mutations can trigger genetic disorders such as cancer. The test made around Pacific Ocean, were done by three countries, **U.K**, **France**, and **U.S**. However, U.s. made the majority of these tests. In addition to harmful and hazardous effect on human health, these nuclear explosions have harmed our environment. Mostly, nuclear test were done in oceans. Ongoing observations and research indicate that Pacific and Atlantic Oceans were detected higher radioactivity than other Oceans. @aarkrog2003input. It can be understood that these two oceans were often used for nuclear experiments so the highest percentage of nuclear radioactivity from these oceans belongs to nuclear explosions made by humans. In addition to oceans, our world's atmosphere can also be effected from nuclear explosions badly. Radioactivity that occurs when a nuclear explosion takes place can play an important role on climate changes that occur due to chancing the balance of elements in **atmosphere** and radioactive pollution. @pruavualie2014nuclear quote: "The indirect transfer of radionuclides into the geospheres and their accumulation in living cells, by way of the food chain, was yet another form of radioactive contamination of the marine and terrestrial ecosystems. One of the most representative examples is the isotope 14C released into the atmosphere during nuclear tests, which is
later integrated into the CO2, and then reaches the marine environment, by means of the ocean–atmosphere gas exchange, or the biosphere through the process of photosynthesis." In this article it is also quoted that most of these nuclear test and the most harmful ones were conducted by **Soviet Union**, a socialist union consisted of 15 countries, collapsed in 1991, and the **U.S**. When all articles that I have reviewed taken into account, the hazard of nuclear explosions for both living creatures and environment can be understood easily. However, since the research question, **Who is more responsible**, is not that easy. When the article @yang2003worldwide is examined, quote: "Since then there is evidence that 2039
additional explosions have been conducted by seven countries (China, France, India, Pakistan, the Soviet Union, the United Kingdom, and the United States) during 1945-1998, according to information in the Nuclear Explosion Database at the Center for Monitoring Research (CMR)." 1056 nuclear explosions were made by U.S and 715 by the Soviet Union, it is clear and easy to say by accordance of numerical observations made and recorded the U.s seems to be responsible for biological and environmental damage that occurred due to explosions. Since, in the article @pruavualie2014nuclear clears that the areas the **U.S** made nuclear test in its own mainland some disorders that have a huge relations with radioactivity such as **Thyroid Cancer** has been more common since the nuclear test had begun. However, to speak in more certain terms, more research and observations are needed.
    




\newpage
# References {#references}
<div id="refs"></div>

